### PR TITLE
Create setup.py

### PR DESCRIPTION
**Pull request by lihaoyi**
Skeletal setup.py that should be enough to put this on PyPI, with some tweaking.

### CODE REVIEW

**Comment by jaredly** [comment]
## awesome thanks!  I'll pull this in tomorrow. 

Jared

**Comment by lihaoyi** [comment]
Would be great if we could have this on PyPI some day =D

**Comment by jaredly** [comment]
totally put it up yesterday =) https://pypi.python.org/pypi/PJs/0.0.0

**Comment by jaredly** [comment]
## isnt it now? 

Jared

**Comment by lihaoyi** [comment]
Yeah it is, I see it! It appears it didn't pick up the non-python folders (e.g. jslib, data, templates). I'm looking into this now

**Comment by jaredly** [comment]
good catch! Just fixed that, and pushed up the full package.

**Comment by lihaoyi** [comment]
The stuff's all in the package, but it's not playing nicely with pip; for some reason it's not installing the non `*.py` files when pip pulls it in

**Comment by lihaoyi** [comment]
I guess ideally all the stuff in `jslib` would be accessible through the python modules like `js_reserved.txt` is; otherwise I expect a lot of pain getting my code to look for the `*.js` files in your package, even if they do get properly installed. Perhaps `jslib/` could be moved inside `pjs/`?

**Comment by lihaoyi** [comment]
Looks like you need a `include_package_data=True` or a `package_data` directive in the `setup`:

http://pythonhosted.org/distribute/setuptools.html#including-data-files

**Comment by jaredly** [comment]
Hmm right. Looking into this

**Comment by jaredly** [comment]
Ok, I did a bit of file rearranging. Now pip grabs everything.

To use your generated files, though, you want to copy pjslib.js to wherever you need it so you can include it along with your generated files. pjslib can be found in /pjs/data/pjslib.js

**Comment by lihaoyi** [comment]
It works! I just removed PJs entirely from my source tree (woot) and pip does the right thing.

Here's the project I was using it for:

https://github.com/lihaoyi/macropy#js-snippets

**Comment by jaredly** [comment]
WoW! That looks ridiculously awesome!
I've always been jealous of scheme's macros =) looks like this is bringing
python up to speed

**Pull request merged**
